services:
  db:
    image: mariadb:lts
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env

  redis:
    image: redis:alpine

  app:
    image: nextcloud:apache
    depends_on:
      - redis
      - db
    volumes:
      - nextcloud:/var/www/html
      - /path/to/file:/path/to/file
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - .env
    ports:
      - 8090:80

  cron:
    image: nextcloud:apache
    depends_on:
      - redis
      - db
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh

volumes:
  nextcloud:
  db:
